#:schema node_modules/wrangler/config-schema.json
name = "free"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[ai]
binding = "AI"

[[r2_buckets]]
bucket_name = ""
binding = "BUCKET"

[vars]
CLOUDFLARE_ACCOUNT_ID = ""
